svc:
  port: 3030
  db:
    mongo:
      url: "${MONGO_URL}"
    redis:
      url: "${REDIS_URL}"
  rnd:
    rndorg:
      enabled: true
      token: "${RANDOMORG_TOKEN}"
    urandom:
      enabled: true
  stt:
    enabled: true
  csot:
    token: "${CROSS_SERVER_TOKEN}"
  auth:
    session_secret: "${SESSION_SECRET}"
    session_ttl_sec: ${SESSION_TTL_SEC:-604800}
